name: Deploy to Elastic Beanstalk (Docker)

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::153227618564:role/Egg-PaperTrail
        aws-region: eu-central-1
        audience: sts.amazonaws.com

    - name: Build & zip Docker app
      run: |
        zip -r docker-app.zip . -x "*.git*" -x "target/*"

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        application_name: PaperTrailBot
        environment_name: PaperTrailBot-env
        version_label: ${{ github.sha }}
        region: eu-central-1
        deployment_package: docker-app.zip
